language: python

python:
    - 3.7
    - 3.6
    - 3.5

install:
    - pip install -r requirements.txt

script:
    - coverage run --source=atomium -m unittest discover tests

after_success:
  - coveralls
