language: python

python:
    - 3.6
    - 3.7
matrix:
  include:
    - python: 3.8
      dist: xenial
      sudo: true

install:
    - pip install -r requirements.txt

script:
    - coverage run --source=atomium -m unittest discover tests

after_success:
  - coveralls
